### PR TITLE
Updating button selectors for hotkey mapping

### PR DESCRIPTION
**Pull request by mmellado**
Update button selectors for hotkey mapping

Updating the selectors for media keys and thumbs up/down to match with the new version of Google Play Music.
- Author: Marcos Mellado marcos@mellados.com

### CODE REVIEW

**Comment by jiri-janousek** [comment]
Hello. Thanks for your pull request. Could you reformat its description according to a draft of [Contributor guidelines](https://github.com/tiliado/nuvolaplayer/issues/128) (section Pull Requests)? Thanks :-)

**Comment by mmellado** [comment]
Sorry about that! I'll update my pull request over the weekend. This is actually my very first time contributing to anything through github so I'm very new to this process. To fix this I just need to do a git commit --amend right?

**Comment by jiri-janousek** [comment]
> To fix this I just need to do a git commit --amend right?

You don't have to amend the commit message. Just change text of the description of this pull request at GitHub website (the first comment) so I can copy-and-paste it without modifications and save some time.

**Comment by mmellado** [comment]
Updated comment :)

**Comment by jiri-janousek** [comment]
Merged. I've changed the summary to "Update selectors of media actions and rating" as there is no hotkey mapping in the scripts actually (the hotkey mapping occurs elsewhere). Thanks for your pull request :+1:

**Pull request merged**
